### ISSUE TITLE
upload big file failed

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#104]
`
      .map(POST, "/upload", request -> {
        Path path = Path.of("upload");
        Promise<HttpResponse> upload_successful = request.handleMultipart(MultipartDecoder.MultipartDataHandler.file(fileName ->
            ChannelFileWriter.open(executor, path.resolve(System.currentTimeMillis() + ""))
          )
        ).map($ -> HttpResponse.ok200().withPlainText("Upload successful"));

        upload_successful.whenComplete((resp, error) -> {
          System.out.println("resp");
        }).whenException(err -> {
          err.printStackTrace();
        });

        return upload_successful;
      });
`
I tried to upload win11.is, size is 4+GB.
"Resp" was printed three times, upload dir has three small files, 
Browser network tab display error(net::ERR_CONNECTION_ABORTED)

**Comment by eduard-vasinskyi** [comment]
Hello, @zhangtianxiao

Thank you for spotting that! Maximum HTTP body size is limited to ~2GB (`int` max size). The upload was initiated 3 times due to browser request retries. 

We have increased the limit to the maximum `long` value. That should be sufficient for very large file uploads.

This change is going to be included as a part of a v4.4 release.
