### ISSUE TITLE
Looks like a bug of activej-bytebuf&activej-http

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#129]

**Comment by zhangtianxiao** [comment]
exception occurred when i called  `client.request(httpRequest)`,
// io.activej.http.MalformedHttpException: Incomplete HTTP message
next call that, returned a bytebuf, bug it's refs is -1 in debug view
because I enable pool's registry, I found it

**Comment by zhangtianxiao** [comment]
I provide some information that may be useful.
I start multiple thread async http server by primaryServer.
AsyncHttpClient created with  primary thread.
When using httpclient, in the work thread.

**Comment by zhangtianxiao** [comment]
And, I use kotlin coroutine to optimize  <Promise>
```kotlin
suspend fun <T> Promise<T>.await(): T = when {
  isComplete -> result
  isException -> throw exception
  else -> suspendCancellableCoroutine { cont: CancellableContinuation<T> ->
    whenComplete { r, e ->
      if(r is ByteBuf){
        println("debug")
      }
      if (e == null) cont.resume(r)
      else cont.resumeWithException(e)
    }
  }
}
```

**Comment by zhangtianxiao** [comment]
I know why, before kotlin coroutline resume, `io.activej.http.HttpMessage#recycle` will call `bytebuf.recycle () `,
How to solve it? I'm very distressed.
Thank you

**Comment by zhangtianxiao** [comment]
I tried use normal code no coroutine
```kotlin
        Promise.ofCallback { promise ->
          client.request(httpRequest).whenComplete { resp: HttpResponse, e: java.lang.Exception? ->
            if (e == null) {
              println("resp.getCode(): " + resp.code)
              resp.loadBody().whenComplete { buf: ByteBuf, e2: java.lang.Exception? ->
                if (e2 == null) {
                  promise.post(HttpResponse.ok200().withBody(buf))
                } else promise.postException(e2)
              }
            } else promise.postException(e)
          }
        }
```
Exception will still occur
Does this mean I only copy the bytebuf from client
I remember the document mentioned ownership

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao 

HTTP client has indeed ownership of HTTP response byte buf. It recycles this byte buf just as soon as a request has been completed. This ensures that there will be no “hanging” unrececlyd byte bufs.

There are 2 ways how you can handle this:
1. Take an ownership of HTTP response body byte buf. This can be done by calling `HttpMessage#takeBody` on an `HttpResponse`. This way you extract a body byte buf from an `HttpResponse` and now your code has an ownership of this byte buf. You will have to recycle it once not needed. Here is how your code can look:
```java
Promise.ofCallback { promise ->
    client.request(httpRequest).whenComplete { resp: HttpResponse, e: java.lang.Exception? ->
        if (e == null) {
            println("resp.getCode(): " + resp.code)
            resp.loadBody().whenComplete { $: ByteBuf, e2: java.lang.Exception? ->
            if (e2 == null) {
	        // notice resp.takeBody() instead of the original loaded body
                promise.post(HttpResponse.ok200().withBody(resp.takeBody())) 
            } else promise.postException(e2)
          }
       } else promise.postException(e)
   }
}
```
2. You can “copy” an HTTP response byte buf so that the HTTP client does not automatically recycle a copy. You can do this by calling `ByteBuf#slice` method that returns a new byte buf. Although, a byte buf is not actually copied, but rather you get a link to the original byte buf with its own `tail` and `head` pointers. The original byte buf will be recycled only when it is actually recycled as well as all the sliced byte bufs are also recycled. This is why you still have to recycle a byte buf returned by the `slice()` method. Here is how your code may look:
```java
Promise.ofCallback { promise ->
    client.request(httpRequest).whenComplete { resp: HttpResponse, e: java.lang.Exception? ->
        if (e == null) {
            println("resp.getCode(): " + resp.code)
            resp.loadBody().whenComplete { buf: ByteBuf, e2: java.lang.Exception? ->
            if (e2 == null) {
	       // notice buf.slice() call
               promise.post(HttpResponse.ok200().withBody(buf.slice())) 
             } else promise.postException(e2)
          }
       } else promise.postException(e)
   }
}
```

*PS. I can see that you use a byte  buf returned by the HTTP response as a body to a new `HttpResponse` as in `HttpResponse.ok200().withBody(buf)`. If this response will be then returned from an `AsyncServlet` of HTTP server you won’t have to recycle it manually. An HTTP server will automatically recycle the body once it writes an HTTP response.*

*PSS. For development purposes, you can use the VM option `-Dchk=on` to enable ActiveJ checks for your code that may help detect incorrect API usage, unsatisfied preconditions or help with detecting usage of recycled byt bufs early. Although, do not use this option in production as additional checks may hurt the performance a bit.*

**Comment by eduard-vasinskyi** [comment]
@zhangtianxiao
I have checked request/response body handling code once again and can confirm that there is no bug. We use both HTTP client and server on production to handle billions of HTTP requests, so we would notice a bug much earlier if it was present.
 

By the way, I believe you can greatly simplify the usage of an HTTP client. Just use `.then()`/`.map()` methods instead of a `.whenComplete()`:
```java
client.request(httpRequest)
     .whenResult(resp -> System.out.println(resp.getCode()))
     .then(resp -> resp.loadBody()
           .map(body -> HttpResponse.ok200().withBody(body.slice())));
 ```
You can take a look at other examples for [HTTP](https://activej.io/http/examples) or [Promises](https://activej.io/async-io/promise) to see how Promise API may simplify asynchronous request handling.

**Comment by zhangtianxiao** [comment]
Thank you for your reply. I already understand
