### ISSUE TITLE
Best practices for closing event loop?

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#130]
fs, httpclient, httpserver, or others, will depend eventloop, 
what's the best Best practices for closing event loop?

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

[Eventloop](https://github.com/activej/activej/blob/master/core-eventloop/src/main/java/io/activej/eventloop/Eventloop.java) runs until it has tasks to execute. In other words, `eventloop.run()` call will block until Eventloop executes all of the tasks (it is the only blocking operation in Eventloop-based approach).

However you can make Eventloop run even if there are no tasks queued by executing `eventloop.keepAlive(true)`. If that is the case, you can call `eventloop.keepAlive(false)` afterwards to make Eventloop run until there are tasks to be processed. 

A best practice would be to use [ActiveJ Launcher](https://activej.io/boot/launcher) in combination with [ActiveJ Inject](https://activej.io/inject). This way Eventloop lifecycle is implicitly handled by [ServiceGraph](https://activej.io/boot/servicegraph), so you do not need to “stop” Eventloop by yourself.

If you need to forcibly stop the execution of Eventloop (disregarding tasks that may still be executed), you can call `eventloop.breakEventloop()`. This will make Eventloop finish executing tasks within the current loop and stop afterwards.

**Comment by zhangtianxiao** [comment]
@eduard-vasinskyi  I tried, but, InetAddress was not released, `ava.net.BindException: Address already in use`,  I need to close it manually;

Is there a way to wait for all tasks to be completed, but eventloop  is  one thread only, If I call sleep to wait, will block eventloop, I'worry....

**Comment by eduard-vasinskyi** [comment]
@zhangtianxiao
If you use one of our servers (e.g. [AsyncHttpServer](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/AsyncHttpServer.java), [ActiveFsServer](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/tcp/ActiveFsServer.java), [RpcServer](https://github.com/activej/activej/blob/master/cloud-rpc/src/main/java/io/activej/rpc/server/RpcServer.java), etc.) they all extend [AbstractServer](https://github.com/activej/activej/blob/master/core-net/src/main/java/io/activej/net/AbstractServer.java) class. AbstractServer has a `close()` method that once called closes underlying server sockets. So you would need to call server.close() to “stop” the server. After the server is closed Eventloop will process remaining server-related tasks and then will gracefully shutdown itself (assuming there are no other tasks to process, from other components, etc.).

As I’ve stated before, you can use [ActiveJ Launcher](https://activej.io/boot/launcher) in combination with [ActiveJ Inject](https://activej.io/inject) to automatically handle stopping of services (including servers).

I didn’t quite get the second question. You already wait for tasks to be completed when you call `eventloop.run()` since it blocks until all tasks are completed.
