### ISSUE TITLE
A feedback on FS

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#133]
```java
  public static void main(String[] args) {
    Eventloop eventloop = Eventloop.create().withCurrentThread();
    ExecutorService executorService = Executors.newCachedThreadPool();
    LocalActiveFs fs = LocalActiveFs.create(eventloop, executorService, Path.of("D:/"))
    fs.download("/test.jpg").whenComplete((t, e) -> {
      System.out.println(t);
    });
    fs.copy("/test.jpg", "/test.jpg.copy").whenComplete((t, e) -> {
      System.out.println("???");
    });
    eventloop.run();
  }
```
Just copy a file, but, io.activej.fs.LocalFileUtils#ensureTarget, there  will not break/return, 
 default value of tempdir is `D:/.upload`, If I call `.withTempDir(Path.of("D:/temp"));` , copy will done.
It seems that the creation of the directory has failed because of the decimal point.
You can close this issue directly.
os: Windows10
activej version: 5.0

**Comment by zhangtianxiao** [comment]
@eduard-vasinskyi

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

Since [LocalActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/LocalActiveFs.java) implements the [EventloopService](https://github.com/activej/activej/blob/master/core-promise/src/main/java/io/activej/async/service/EventloopService.java) interface, it has methods `start()` and `stop()` to control a lifecycle of local file system. You need to call `fs.start()` before using `LocalActiveFs` and wait for it to finish. What this method does is it initializes a temporary directory for the file system (`.upload` by default).

You can modify your code so that it looks something like this:
```java
Eventloop eventloop = Eventloop.create().withCurrentThread();
ExecutorService executorService = Executors.newCachedThreadPool();
LocalActiveFs fs = LocalActiveFs.create(eventloop, executorService, Path.of("D:/"));
 
fs.start()
     .whenResult(() -> {
        fs.download("test.jpg")
              .whenResult(supplier -> System.out.println("Download successful"))
              .whenException(e -> System.err.println("Download failed: " + e));
        fs.copy("test.jpg", "test.jpg.copy")
              .whenResult(() -> System.out.println("Copy successful"))
              .whenException(e -> System.err.println("Copy failed: " + e));
     })
 .then(($, e) -> fs.stop());
 
eventloop.run();
executorService.shutdown();
 ```
Notice that we first call `fs.start()` and download/copy is initialized only after `LocalActiveFs` has started. After the job is done and we do not need `LocalActiveFs` anymore we can stop it: `.then(($, e) -> fs.stop())`.

I have also removed slashes from filenames (`/test.jpg` -> `test.jpg`, etc.) as they are not necessary. 

Also, `ActiveFs#download` returns a [ChannelSupplier<ByteBuf>](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/ChannelSupplier.java). This is part of our asynchronous streaming module called Communicating Sequential Process (CSP). You can read more about CSP [here](https://activej.io/async-io/csp). In short, you need to query a channel supplier to get data from it or you can simply transform it to a `ByteBuf` that holds file content like this:
```java
supplier.toCollector(ByteBufs.collector())
     .whenResult(byteBuf -> {
        String content = byteBuf.asString(StandardCharsets.UTF_8);
        System.out.println(content);
     })
```
