### ISSUE TITLE
Building activej-fs may fail because of test execution order

### ISSUE THREAD

**Issue by ewie** [activej/activej#139]
The build succeeds when running tests via IntelliJ (_Run 'All Tests'_ with all modules) but fails when using `mvn clean verify`.

The difference is that IntelliJ executes tests in alphabetical order (fully qualified class name), whereas `maven-surefire-plugin` executes them in filesystem order by default (https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder). This can be changed with `-Dsurefire.runOrder=alphabetical`.

I identified test classes `ClusterRepartitionControllerTest` and `FsExceptionCodecTest` for a minimal example:
```console
mvn test -pl cloud-fs -Dtest=ClusterRepartitionControllerTest,FsExceptionCodecTest
mvn test -pl cloud-fs -Dtest=ClusterRepartitionControllerTest,FsExceptionCodecTest -Dsurefire.runOrder=alphabetical
```
The first build fails in my case (Linux with ext4), whereas the second succeeds.

This doesn't solve the underlying problem though. Adding `ByteBufRule` to `FsExceptionCodecTest` fixes the build without an explicit test execution order:
```java
@ClassRule
public static final ByteBufRule byteBufRule = new ByteBufRule();
```
But I don't know if this is the only class where this change is required without checking every possible permutation of test classes. It's also error-prone to manually add this rule where necessary.

This is based on 6b07ac4b9a5d92fd257f3a13e79f15499a1101b9 plus the changes in #138.

**Comment by eduard-vasinskyi** [comment]
Hi, @ewie

Thank you for spotting that!

`FsExceptionCodecTest` is indeed implicitly initializes `ByteBufPool` class. That is why a `ByteBufRule` class rule should be added to the test. 

I have found other test classes that initialize `ByteBufPool` class while running tests using fork mode “Class” and setting up a few breakpoints.

Additionally, I have added test system variables from `ByteBufRule` class directly to the \<systemPropertyVariables> of a surefire plugin in pom.xml. (We still need to add `ByteBufRule` to the tests since IntelliJ IDEA ignores \<systemPropertyVariables> when running ‘All tests’)

You can find those changes in the ‘master’ branch. 


```mvn test -pl cloud-fs -Dtest=ClusterRepartitionControllerTest,FsExceptionCodecTest ``` now executes without an error.
