### ISSUE TITLE
Ambiguous services found

### ISSUE THREAD

**Issue by vencivenc** [activej/activej#149]
Hello,

I'm trying to run the example [here](https://github.com/activej/activej/blob/master/examples/core/sql/src/main/java/advanced/JdbcPooledSqlLauncher.java) but I receive the following error and I have no idea what I'm doing wrong or it's a bug in the framework itself?

``` 
Exception in thread "main" java.lang.IllegalArgumentException: Ambiguous services found for class com.zaxxer.hikari.HikariDataSource : [interface java.io.Closeable, interface javax.sql.DataSource]. Use register() methods to specify service.
	at io.activej.service.ServiceGraphModule.doLookupAdapter(ServiceGraphModule.java:600)
	at io.activej.service.ServiceGraphModule.lookupAdapter(ServiceGraphModule.java:570)
	at io.activej.service.ServiceGraphModule.getServiceOrNull(ServiceGraphModule.java:542)
	at io.activej.service.ServiceGraphModule.getCombinedServiceOrNull(ServiceGraphModule.java:474)
	at io.activej.service.ServiceGraphModule.doStart(ServiceGraphModule.java:428)
	at io.activej.service.ServiceGraphModule.doStart(ServiceGraphModule.java:401)
	at io.activej.service.ServiceGraphModule.lambda$serviceGraph$3(ServiceGraphModule.java:283)
	at io.activej.service.ServiceGraph.startFuture(ServiceGraph.java:278)
	at io.activej.service.ServiceGraphModule$1.start(ServiceGraphModule.java:296)
	at io.activej.launcher.Launcher.startServices(Launcher.java:235)
	at io.activej.launcher.Launcher.launch(Launcher.java:158)
	at ship.cars.dataone.WebApp.main(WebApp.java:73)
```

My snippet

```Java
import com.zaxxer.hikari.HikariDataSource;
import io.activej.config.Config;
import io.activej.http.AsyncServlet;
import io.activej.http.HttpResponse;
import io.activej.inject.annotation.Inject;
import io.activej.inject.annotation.Provides;
import io.activej.inject.module.AbstractModule;
import io.activej.inject.module.Module;
import io.activej.inject.module.Modules;
import io.activej.launcher.Launcher;
import io.activej.launchers.http.MultithreadedHttpServerLauncher;
import io.activej.promise.Promise;
import io.activej.service.ServiceGraphModule;
import ship.cars.dataone.utils.HikariConfigConverter;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;


public class WebApp extends MultithreadedHttpServerLauncher {
    @Inject
    DataSource dataSource;

    @Override
    protected void run() {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()
        ) {
            statement.executeUpdate("SELECT NOW();");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void onStart() {
        System.out.println("TABLES BEFORE:");
    }

    @Override
    protected Module getOverrideModule() {
        return Modules.combine(
                ServiceGraphModule.create(),
                // db module
                new AbstractModule() {
                    @Provides
                    DataSource dataSource(Config config) {
                        HikariConfigConverter converter = HikariConfigConverter.create().withAllowMultiQueries();
                        return new HikariDataSource(config.get(converter, "hikari"));
                    }
                }
        );
    }

    @Provides
    AsyncServlet servlet() {
        return request -> Promise.of(
                HttpResponse.ok200()
                    .withPlainText("Hello, World!"));
    }

    public static void main(String[] args) throws Exception {
        Launcher launcher = new WebApp();
        launcher.launch(args);
    }
}
```

Thank you in advance :)

**Comment by vencivenc** [comment]
Resolved it by wrapping the `HikariDataSource` in class which implements only `DataSource` but I think there should be a better solution 🤣 

```java
import javax.sql.DataSource;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.util.logging.Logger;

public final class MyDataSource implements DataSource {

    private final DataSource dataSource;

    public MyDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public static MyDataSource create(DataSource dataSource) {
        return new MyDataSource(dataSource);
    }

    @Override
    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }

    @Override
    public Connection getConnection(String username, String password) throws SQLException {
        return dataSource.getConnection(username, password);
    }

    @Override
    public PrintWriter getLogWriter() throws SQLException {
        return dataSource.getLogWriter();
    }

    @Override
    public void setLogWriter(PrintWriter out) throws SQLException {
        dataSource.setLogWriter(out);
    }

    @Override
    public void setLoginTimeout(int seconds) throws SQLException {
        dataSource.setLoginTimeout(seconds);
    }

    @Override
    public int getLoginTimeout() throws SQLException {
        return dataSource.getLoginTimeout();
    }

    @Override
    public Logger getParentLogger() throws SQLFeatureNotSupportedException {
        return dataSource.getParentLogger();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return dataSource.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return dataSource.isWrapperFor(iface);
    }
}

```

**Comment by eduard-vasinskyi** [comment]
Hi, @vencivenc

Thank you for providing a snippet, this has greatly helped in pinpointing a problem.

Since `MultithreadedHttpServerLauncher` uses a [ServiceGraphModule](https://github.com/activej/activej/blob/6d151e5bbfb7340e5baef07495e9741e3cf4ab75/boot-servicegraph/src/main/java/io/activej/service/ServiceGraphModule.java), all of the provided services are started/stopped by the [ServiceGraph](https://activej.io/boot/servicegraph). A `ServicGraphModule` contains pre-registered `ServiceAdapters` that describe how a start/stop operation should be performed for a certain class. 

A `HikariDataSource` implements both `DataSource` and `Closeable` interfaces. Service graph  cannot choose whether it should start/stop a `HikariDataSource` as a `DataSource` or as a `Closeable`. You need to manually define a service adapter for `HikariDataSource` as a combination of `Closeable` and `DataSource` service adapters.

You can modify your snippet by replacing the `ServiceGraphModule.create()` line with:
```java
ServiceGraphModule.create()
       .register(HikariDataSource.class, ServiceAdapters.combinedAdapter(
               ServiceAdapters.forCloseable(),
               ServiceAdapters.forDataSource()))
```
 
_BTW, you should probably replace `statement.executeUpdate("SELECT NOW();")` with `statement.executeQuery("SELECT NOW();")`_

**Comment by vencivenc** [comment]
Thank you for the detailed explanation @eduard-vasinskyi , that fully resolved my issue.

One more thing which is not related to this topic. 

What would be the recommended setup if we want to deploy small application with high http traffic on k8s which scales horizontally with ActiveJ? How many resources should we allocate? What is a better choice `HttpServerLauncher` or `MultithreadedHttpServerLauncher` and if `MultithreadedHttpServerLauncher` how many workers should we use (I guess that depends on the resources which we should allocate for each container)?

I guess thats for a different topic, if you want we can create a separate discussion about it?

Thank you :)

**Comment by eduard-vasinskyi** [comment]
The `prom` promise has timed out as the blocking code took more than 1 second to execute. The promise has been completed with a timeout exception instead of a result. That’s why you receive `null` as a result of a promise. If you call `prom.getException()` instead, you will receive an `AsyncTimeoutException`.

You can check whether a promise has already been completed using `Promise#isComplete` method. You can also use `Promise#isResult` and `Promise#isException` methods to determine whether a promise has been completed successfully or not.

However, it is not very common to use `getResult()`/`getException()` methods in an application code. Normally you would use `Promise#whenComplete`, `Promise#whenResult`, `Promise#whenException` methods to add callbacks to the promise execution. (note, that those callbacks would be executed inside the eventloop thread)

**Comment by eduard-vasinskyi** [comment]
Environment resources are dependent on business logic as well application architecture. 

- If the main bottleneck is a business logic and not HTTP processing, then a single-threaded HTTP server should be enough
- This is also the case if your business logic is executed within thread pools / executors
- You would need a multithreaded HTTP server if business logic processing occurs within an eventloop thread

The last approach is optimal and recommended for ActiveJ applications as it ensures minimal latency and eliminates multithreading overhead. The approach is also fully compatible with ActiveJ Inject as it allows the creation of an identical set of components for each worker thread.

With a multithreaded approach you can think of ActiveJ application as a group of node.js applications contained inside a single JVM. Each such application  can modify a common state and operate on thread-safe singletons.

But for starters, you can use a single threaded server. After you get familiar with an asynchronous code that uses our promises, you can benchmark your application and make it multi-threaded if needed.

**Comment by vencivenc** [comment]
Thank you for the recommendations @eduard-vasinskyi !

I have created one [example](https://github.com/vencivenc/activej-examlpe ) using your guidance. 
Can you please check it and see if the concept and the way I use promises, redis, datasource & serialization is right?
Then you can fork it and use it as example in your documentation if you want.

**Comment by eduard-vasinskyi** [comment]
This is a good example of using ActiveJ with external DBs.

Although, there are a few remarks:
- You do not need to add `activej-serializer` and `activej-dataflow` modules as your example does not use those
- You are not required to use the `DSL-JSON` library for JSON serialization. ActiveJ allows you to use any JSON library of your choice.
- Routing servlet multibinder seems like an overkill for such a small application, as you have only one `RoutingServlet` provided (meaning no conflicts).
- In a production code you may consider reusing Redis connections rather than closing those on each request.
- In `VehicleServiceImpl#getYears` you ignore the result of a `redis.putSting()` call. If that is intended, you can use `Promise#map` instead of `Promise#then` and skip wrapping the result using `Promise#of`.
- You could do something like this in the `RedisImpl` class:
```java
redisClient.connect()
       .then(connection -> connection.cmd(...)
              .whenComplete(connection::quit)));
```
as sometimes you lose the result of a command execution (like in `RedisImpl#putSting` method, also note a typo in the method name).
 
We will think about using a fork of this example as part of our tutorials/documentation.

**Comment by vencivenc** [comment]
Again, very helpful @eduard-vasinskyi !

- Will remove both unused dependencies
- Wanted to try DSL-JSON because it is said to be the fastest JVM JSON library
- About the multibinder, just wanted to show how one big application with many modules would look like :)
- About the redis, I tried to refactor it and came to that but the performance degraded a lot (from ~3ms to ~500ms) and I guess it because of the eventloop.

```java
package org.example.activej.modules.common.redis;

import io.activej.async.service.EventloopService;
import io.activej.eventloop.Eventloop;
import io.activej.promise.Promise;
import io.activej.redis.RedisClient;
import io.activej.redis.RedisConnection;
import io.activej.redis.RedisRequest;
import io.activej.redis.RedisResponse;
import org.jetbrains.annotations.NotNull;

public class RedisImpl implements Redis, EventloopService {

    private final RedisClient redisClient;

    private final Eventloop eventloop;

    private RedisConnection redisConnection;

    public RedisImpl(Eventloop eventloop, RedisClient redisClient) {
        this.eventloop = eventloop;
        this.redisClient = redisClient;
    }

    @Override
    public Promise<String> getString(String key) {
        return this.redisConnection.cmd(RedisRequest.of("GET", key), RedisResponse.BYTES_UTF8);
    }

    public Promise<Void> putString(String key, String value) {
        return putString(key, value, null);
    }

    public Promise<Void> putString(String key, String value, Integer ttl) {
        RedisRequest request = ttl == null ? RedisRequest.of("SET", key, value) : RedisRequest.of("SET", key, value, "EX", String.valueOf(ttl));

        return this.redisConnection.cmd(request, RedisResponse.OK);
    }

    @Override
    public @NotNull Eventloop getEventloop() {
        return eventloop;
    }

    public @NotNull Promise<RedisConnection> start() {
        return redisClient.connect().whenResult(redisConnection -> this.redisConnection = redisConnection);
    }

    @Override
    public @NotNull Promise<?> stop() {
        return redisConnection.quit();
    }
}
```

Is this the right way of creating a reusable redis connection?
Should I create a pool of redis connections? or I should somehow initialise RedisConnection for each Eventloop (Worker), or this initialisation is done automatically for each Worker when its spawned?

**Comment by eduard-vasinskyi** [comment]
I have also noticed that your setup does not utilize a multithreaded launcher. Your components work on top of a primary eventloop, while worker threads are not processing anything.

To fix this you should add [@Worker](https://github.com/activej/activej/blob/master/boot-workers/src/main/java/io/activej/worker/annotation/Worker.java) annotation to the [@Provides](https://github.com/activej/activej/blob/master/core-inject/src/main/java/io/activej/inject/annotation/Provides.java) annotated methods of `RedisClient`, `Redis`, `VehicleDao`, `VehicleService`, `VehicleController` and a `RoutingServlet`. You should also replace the 
```java
.bind(AsyncServlet.class).to(RoutingServlet.class)
```
call with:
```java
.bind(AsyncServlet.class).to(RoutingServlet.class).in(Worker.class)
```

This way each component will be bound to a worker eventloop and the load would be distributed evenly.


When I talked about reusing Redis connections, I meant something along the lines of a pool of connections (similar to HikariCP) rather than reusing a single connection. You probably get the performance drop because a single connection operates in the pipelined mode and each consequent request waits for previous requests to complete.

**Comment by vencivenc** [comment]
I see, @eduard-vasinskyi 

So something like [JedisPool](https://www.baeldung.com/jedis-java-redis-client-library) should work?
What are the advantages of using your RedisClient over something like JedisPool for example?
