### ISSUE TITLE
Streaming/Rx/Ix Abstractions

### ISSUE THREAD

**Issue by sirinath** [activej/activej#15]
Ix/Rx/Streaming (http://reactivex.io/, https://projectreactor.io/, https://rsocket.io/) abstraction is one of the most convenient to use and supported in some extend in frameworks like Micronaut, Vertx, etc.

Can we have an Ix/Rx/Streaming module throughout integration.

**Comment by eduard-vasinskyi** [comment]
Hello, @sirinath 
ActiveJ provides several modules for streaming purposes. Those are:

- [Datastream module](https://activej.io/datastream.html) - that provides a highly optimized streaming with back pressure control
- [CSP module](https://activej.io/csp.html) - a more convenient asynchronous streaming

If you need to stream data, you can use these modules instead of Rx/Ix abstractions
