### ISSUE TITLE
Some questions about code design

### ISSUE THREAD

**Issue by zhangtianxiao** [activej/activej#153]
why `code` of HttpResponse is final.
why not public `attachments` of HttpMessage.
It seems a little inconvenient.
Thanks.

**Comment by eduard-vasinskyi** [comment]
Hi, @zhangtianxiao

>why code of HttpResponse is final.

Why should `HttpResponse` class be non-final? It is a concrete implementation of `HttpMessage`, managed by the `AsyncHttpClient`/`AsyncHttpServer`. It is not meant to be extended.
What kind of functionality are you missing?

>why not public attachments of HttpMessage.

Following the encapsulation OOP principle we’ve encapsulated the attachment map while providing API for setting/accessing HTTP message attachments. The attachment map itself is `Map<Object, Object>` due to implementation feature while API provides more convenient typed accessors. Could you provide an example of inconvenient API usage? Maybe we could improve it.

**Comment by zhangtianxiao** [comment]
My description is not very accurate.
Code like this.
```java
class Controller {
  final HttpRequest req;
  final HttpResponse resp;

  public Controller(HttpRequest req, HttpResponse resp) {
    this.req = req;
    this.req = resp;
  }

  public void setStatus(int code) {
    // before io.activej.http.AsyncServlet.serve return
    // i want change code of resp
    // but "code" is private and final
    resp.code = code;
  }

  public void index() {
    // but "attachments" is not public 
    req.attach("name", "eduard-vasinskyi");
    Map<Object, Object> map = req.attachments;
    renderByTemplateEngine("/index.html", map);
    /*
     <div> your name: ${name} </div>
    * */
  }
}
```

**Comment by eduard-vasinskyi** [comment]
You cannot change the status code of an `HttpResponse`. You would have to construct a new `HttpResponse` out of the existing `HttpResponse` with the correct status code.



HTTP message attachments were never meant to be used as a template engine values map. You can think of attachments as some sort of additional context that you would use if you could not pass the context explicitly. Considering the template engine example, you could attach a template values map to the message attachments as it is an additional context for your business logic.
```java
req.attach("templateValues", new HashMap<>());
...
Map<String, String> templateValues = req.getAttachment("templateValues");
templateValues.put("name", "my name");
...
Map<String, String> templateValues = req.getAttachment("templateValues");
renderByTemplateEngine("/index.html", templateValues);
```
