### ISSUE TITLE
Question: What does @Eager attribute do?

### ISSUE THREAD

**Issue by sirinath** [activej/activej#16]
I have encondeted `@Eager` in the following example:

```java
	@Provides
	@Eager
	AsyncHttpServer server(Eventloop eventloop, AsyncServlet servlet) {
		return AsyncHttpServer.create(eventloop, servlet).withListenPort(PORT);
	}
```

I have not seen this else were any other HTTP example. What does the `@Eager` do?

Is it possible to have a documentation page on all ActiveJ attributes?

**Comment by valerialistratova** [comment]
A binding marked as `eager` will be called for an instance of its object immediately after injector creation. Next calls of `Injector.getInstance` will only retrieve its cached instance. That's why object can't be `[transient](https://github.com/activej/activej/blob/master/core-inject/src/main/java/io/activej/inject/annotation/Transient.java)` and `[eager](https://github.com/activej/activej/blob/master/core-inject/src/main/java/io/activej/inject/annotation/Eager.java)` simultaneously. 

Most of the annotations are described in ActiveInject [Basic](https://inject.activej.io/docs) and [Advanced](https://inject.activej.io/advanced) examples. You can also find a brief javadoc for each annotation in the source code.

**Comment by sirinath** [comment]
@valerialistratova many thanks for the support in finding my way around ActiveJ.

**Comment by valerialistratova** [comment]
@sirinath you're welcome)

**Comment by sirinath** [comment]
I am wondering if you can also help me with: https://github.com/activej/activej/issues/14#issuecomment-654724899
