### ISSUE TITLE
Question: Websocket example

### ISSUE THREAD

**Issue by a1730** [activej/activej#22]
Can you please point me to where I can learn to implement a websocket server using activej?

**Comment by eduard-vasinskyi** [comment]
Hello, @a1730
There is currently no support for WebSocket.
However, we plan to implement WebSocket protocol in future versions of ActiveJ.

**Comment by sirinath** [comment]
@eduard-vasinskyi  This is great news. Since SSE is a very low hanging fruit maybe this can be implemented with it and WebRTC later on. BTW, have you come across [Jooby](https://jooby.io/)? As @a1730 mentioned [here](https://github.com/jooby-project/jooby/issues/1892), ActiveJ can be used as the underlying framework for Jooby this will be great as Jooby gives a higher-level abstraction than what ActiveJ which will make it a lot easier to use. Perhaps ActiveJ team can help integrate it into Jooby.

**Comment by a1730** [comment]
> 
> 
> Hello, @a1730
> There is currently no support for WebSocket.
> However, we plan to implement WebSocket protocol in future versions of ActiveJ.

We just tested the web socket implementation - apologies for the delay, testing with ActiveJ fell off our radar.
All I can say is **Wow!**
ActiveJ is giving Jooby a run for its money in niche areas where we can use either of them. Specifically, if a feature is supported in ActiveJ and Jooby we find that it easier to use ActiveJ, and publish. ActiveJ's minimal dependency on 3rd party libraries is also a blessing (one library to pull)- truthfully was what made us start looking for a Jooby alternative. Jetty/Netty are good, still 3rd party, and Jetty/Netty also bring their 3rd-3rd party friends.

**Comment by a1730** [comment]
I meant to say, Thank you.

**Comment by azzahrah** [comment]
as i know Jooby is Netty base

**Comment by eduard-vasinskyi** [comment]
WebSocket examples can be found here: 
- [WebSocket Ping Client Example,](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/WebSocketPingClientExample.java) 
- [WebSocket Pong Server Example](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/WebSocketPongServerExample.java)
- [WebSocket Echo Client Example](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/WebSocketEchoClientExample.java)
- [WebSocket Echo Server Example](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/WebSocketEchoServerExample.java)
