### ISSUE TITLE
[ActiveFsServer] howto set onFinishUpload handler?

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#55]
When remote computer upload file to ActiveFsServer, howto catch event when upload just finish?

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah
[ActiveFsServer](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/tcp/ActiveFsServer.java) can work with any [ActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/ActiveFs.java) implementation. So if you need to create custom ActiveFs, you can do just that! One way to do so is to use a Decorator pattern. You can create a wrapper that would delegate all method calls to some ActiveFs, and decorate only methods that you need (`upload()` in your case). This approach would allow you to add custom logging, filtering, filename transformations, and other functionality to the [ActiveFsServer](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/tcp/ActiveFsServer.java). There are some pre-built adapters that you can find in [ActiveFsAdapters](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/ActiveFsAdapters.java) class. 
As for adding `onFinishUpload` handler, you may extend [ForwardingActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/ForwardingActiveFs.java) class and override `upload()` method to provide a custom upload finish handler. `upload()` actually returns a Promise of [ChannelConsumer](https://github.com/activej/activej/blob/master/core-csp/src/main/java/io/activej/csp/ChannelConsumer.java). To add a handler that would be called on upload finish you need to transform `ChannelConsumer`’s acknowledgement promise (by calling `consumer.withAcknowledgement(...)`). Acknowledgment promise will be completed once the upload ends either successfully or with an exception. You may log the result or do some other custom action. Here is an example of an adapter that writes upload status on upload finish. You can wrap any [ActiveFs](https://github.com/activej/activej/blob/master/cloud-fs/src/main/java/io/activej/fs/ActiveFs.java) using this adapter and each upload() would end up calling a custom handler on finish.

```
    class CustomActiveFs extends ForwardingActiveFs {
        public CustomActiveFs(ActiveFs peer) {
            super(peer);
        }

        @Override
        public Promise<ChannelConsumer<ByteBuf>> upload(@NotNull String name) {
            return super.upload(name)
                    .map(consumer -> consumer.withAcknowledgement(ack ->
                            ack.whenComplete((result, e) -> {
                                // Your custom handler goes here
                                if (e == null) {
                                    System.out.println("Successful upload");
                                } else {
                                    System.err.println("Upload finished with error: " + e);
                                }
                            })));
        }
    }

```

PS. if you need to call asynchronous code in your handler, use `ack.then()`/`ack.thenEx()` instead of `ack.whenComplete()`.

**Comment by azzahrah** [comment]
@eduard-vasinskyi thank for detail answer...  really nice work with ActiveJ...

**Comment by eduard-vasinskyi** [comment]
We have added a standalone [example](https://github.com/activej/activej/blob/master/examples/cloud/fs/src/main/java/DecoratedActiveFsExample.java) based on this issue

**Comment by azzahrah** [comment]
@eduard-vasinskyi thanks very much this really what we want... thanks...
