### ISSUE TITLE
Deserializing List<Object> problem

### ISSUE THREAD

**Issue by frenz79** [activej/activej#61]
Hi all,
I was really impressed about how serialization is fast (I'm currently using protobuf and SBE), and I'm preparing a POC with Activej serializer, however I have a problem decoding a List<Object> collection where I put different data types.
I encode <Date,Integer,String> elements, but I got <Object,Object,Object> decoded elements that I cannot cast or convert back to the original type.
Am I missing something?
Thanks

**Comment by eduard-vasinskyi** [comment]
Hello, @frenz79 
Could you please provide a snippet that illustrates the issue? I'll take a look

**Comment by frenz79** [comment]
Hi, that's it:

```
public static class TestCase {
		@Serialize(order = 0)
		public int val1;
		@Serialize(order = 1)
		public String val2;
		@Serialize(order = 2)
		public List<Object> val3 = new ArrayList<Object>();
	}
	private static final DefiningClassLoader definingClassLoader = DefiningClassLoader.create();
	private static final BinarySerializer<TestCase> serializerTestCase = SerializerBuilder.create(definingClassLoader)
			.withCompatibilityLevel(CompatibilityLevel.LEVEL_3_LE)
			.build(TestCase.class);
```
	
	public static void main( String arg[] ) throws Throwable {
		
		byte[] buff = new byte[10000];
		TestCase t1 = new TestCase();
		t1.val1 = 123;
		t1.val2 = "456";
		t1.val3.add("789");
		t1.val3.add( Boolean.FALSE );
		t1.val3.add( Long.valueOf(666L) );
		
		serializerTestCase.encode(buff, 0, t1);
		
		TestCase t2 = serializerTestCase.decode( buff, 0 );
		
		System.out.println("val1 = "+t2.val1);
		System.out.println("val2 = "+t2.val2);
		System.out.println("val3 = "+t2.val3);
		System.out.println("val3[0] = "+t2.val3.get(0));
		System.out.println("val3[1] = "+t2.val3.get(1));
		System.out.println("val3[2] = "+t2.val3.get(2));
		
		System.out.println("val3[0] = "+(String)t2.val3.get(0));
		System.out.println("val3[1] = "+(Boolean)t2.val3.get(1));
		System.out.println("val3[2] = "+(Long)t2.val3.get(2));
	}
`
running it i got:

val1 = 123
val2 = 456
val3 = [java.lang.Object@307f6b8c, java.lang.Object@7a187f14, java.lang.Object@6f195bc3]
val3[0] = java.lang.Object@307f6b8c
val3[1] = java.lang.Object@7a187f14
val3[2] = java.lang.Object@6f195bc3
Exception in thread "main" java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String
	at com.unicredit.frpc.msg.FRPCMessage.main(FRPCMessage.java:133)

**Comment by eduard-vasinskyi** [comment]
You need to know the types of elements that would go into the `List` to create a serializer. 
To do so, [ActiveJ Serializer](https://serializer.activej.io/) provides [@SerializeSubclasses](https://github.com/activej/activej/blob/master/core-serializer/src/main/java/io/activej/serializer/annotations/SerializeSubclasses.java) annotation. Using this annotation you may instruct the serializer to serialize a given type as one of the provided types.
As in your case, to serialize a `List<Object>` that may contain `String`, `Long`, `Boolean` values, you have to additionally annotate the `List<Object>` field with annotation:
`@SerializeSubclasses(value = {String.class, Boolean.class, Long.class}, path = 0)`, where:
- **value** is an array of types that would be put into the `List`;
- **path** - is an array of ints that represents a path to the type we need to annotate. Since we want to annotate `Object` in `List<Object>`, the path equals to `{0}` or simply `0`. As List has only one generic type, hence its index is 0. 
If we, for example, needed to serialize a list of lists of objects (`List<List<Object>>`), the path would be equal to `{0, 0}`.

*If you have any more questions, feel free to ask*

**Comment by frenz79** [comment]
Thanks, but I needed a generic collection to store a generic input args to be passed to a method handle invoke, String/Boolean/Long was just a simple testcase.
Is there a way to have a dynamically typed @SerializeSubclasses ?

**Comment by eduard-vasinskyi** [comment]
It is not possible to create a serializer that could magically serialize any arbitrary class. You need to know the class in advance. 
If you know the classes in compile-time, you can pass those classes to `@SerializeSubclasses` annotation, as in the previous example.
If you know the classes in runtime, you could use the `extraSubClassesId` attribute of `@SerializeSubclasses`. Instead of hardcoding an array of classes into the annotation, you can provide some unique String ID, like this:

`@SerializeSubclasses(extraSubclassesId = "list", path = 0)`

When creating a serializer, you can reference this ID and pass a list or an array of required classes:

`SerializerBuilder.create(definingClassLoader)
       .withSubclasses("list", Long.class, Boolean.class, String.class)`

You would have to recreate a SerializerBuilder for each set of classes.

We have added an [example](https://github.com/activej/activej/blob/master/examples/core/serializer/src/main/java/SerializeSubclassesExample.java) that demonstrates how to create a serializer with dynamic subclasses
