### ISSUE TITLE
Request never finishes/responds

### ISSUE THREAD

**Issue by FireMasterK** [activej/activej#62]
```
        Eventloop eventloop = Eventloop.create();
        AsyncHttpServer httpServer = AsyncHttpServer
                .create(eventloop, RoutingServlet.create().map("/streams/:videoId", request -> {
                    try {
                        return HttpResponse.ok200().withPlainText(request.getPathParameter("videoId"));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return null;
                })).withListenPort(Constants.PORT);

        httpServer.listen();

        Thread.sleep(Long.MAX_VALUE);
```

I then open http://127.0.0.1:8080/streams/dQw4w9WgXcQ for example.

I'm on windows, am I doing something wrong?

**Comment by eduard-vasinskyi** [comment]
Hello, @FireMasterK 
You need to call `run()` on the [Eventloop](https://github.com/activej/activej/blob/master/core-eventloop/src/main/java/io/activej/eventloop/Eventloop.java) in order to start it.
`Eventloop#run` method will start an 'endless' cycle, so you can simply replace `Thread.sleep(Long.MAX_VALUE)` with `eventloop.run()`.

You also do not need to wrap getPathParameter() in a try-catch block. It would throw IllegalArgumentException only if you messed up in setting up paths in a RoutingServlet. But you have `/:videoId` mapped, so retrieving a path parameter `videoId` would never throw an exception here.

Also, returning `null` from `AsyncServlet#serve` method would lead to a `NullPointerException` thrown. If you catch an exception in a servlet, you may return either `Promise.ofException(Throwable)` or a custom [HttpResponse](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/HttpResponse.java) (e.g. `HttpResponse.ofCode(404)`)

Here is an updated example:
```
        Eventloop eventloop = Eventloop.create();
        AsyncHttpServer httpServer = AsyncHttpServer
                .create(eventloop, RoutingServlet.create()
                        .map("/streams/:videoId", request ->
                                HttpResponse.ok200()
                                        .withPlainText(request.getPathParameter("videoId"))))
                .withListenPort(8080);

        httpServer.listen();
        eventloop.run();
```

*BTW, you may use our [boot module](https://activej.io/launcher.html) to launch your application. It will wire your components using our [Dependency Injection](https://inject.activej.io/) library. It also automatically handles starting and stopping of your components, that way you do not need to manually call `httpServer.listen()` and `eventloop.run()`*

If you have any more questions about ActiveJ, feel free to ask

**Comment by FireMasterK** [comment]
Thank you, I ended up using the boot module!

I have a few questions:

- How can I initiate a Promise with a function call (that takes a long time)?
- I have to add a header based on the total time it takes to process a request, is there any easier way than doing so than recording the time taken in each route handler?

**Comment by eduard-vasinskyi** [comment]
>How can I initiate a Promise with a function call (that takes a long time)?

To initiate a promise with a function that takes a long time to complete you need to execute the function in another thread (as the Eventloop thread should never be blocked). To do so, you can use either: 
- `Promise.ofBlockingRunnable(Executor, BlockingRunnable)` - if you do not need the result of a function call
- `Promise.ofBlockingCallable(Executor, BlockingCallable)` - if you do need to retrieve the result of a function call

>I have to add a header based on the total time it takes to process a request, is there any easier way than doing so than recording the time taken in each route handler?

You may use a wrapper over [AsyncServlet](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/AsyncServlet.java) to do this. Just write a wrapper that records the time before the request is processed by a servlet. After the request has been processed, a wrapper can map the received HttpResponse by adding a new header that contains the time it took to process the request.
After that, you can wrap any servlet (Routing servlet with mapped paths, for example) and every HTTP response would contain a header, representing the time it took to process the request.
Here is the snippet of such wrapper:
```
public static final class ServeTimeServletDecorator implements AsyncServlet {
        private static final HttpHeader HEADER = HttpHeaders.of("Serve-time");

        private final AsyncServlet servlet;

        public ServeTimeServletDecorator(AsyncServlet servlet) {
            this.servlet = servlet;
        }

        @Override
        public @NotNull Promisable<HttpResponse> serve(@NotNull HttpRequest request) {
            long before = System.currentTimeMillis();
            return servlet.serve(request)
                    .promise()
                    .map(response -> {
                        long serveTime = System.currentTimeMillis() - before;
                        String serveTimeString = String.valueOf(serveTime);
                        HttpHeaderValue headerValue = HttpHeaderValue.of(serveTimeString);

                        return response
                                .withHeader(HEADER, headerValue);
                    });
        }
    }
```
 
>Can the Serializer, serialize objects to JSON (the documentation only shows byte arrays)?

Serializer only serializes data to binary format. You may use your preferable JSON library with ActiveJ to handle JSON processing.

**Comment by FireMasterK** [comment]
Thank you! This is really helpful!
