### ISSUE TITLE
 Can you give an example of how to connect mysql data with persistence layer

### ISSUE THREAD

**Issue by hjldev** [activej/activej#63]
I want to connect to MySQL database and use dependency injection directly. How should I write it

**Comment by eduard-vasinskyi** [comment]
Hello, @hjldev
To work with MySql you can use JDBC API. Since JDBC calls are blocking, you may use either:
- `Promise.ofBlockingRunnable(Executor, BlockingRunnable)` - if you do not need the result of a JDBC call
- `Promise.ofBlockingCallable(Executor, BlockingCallable)` - if you do need to retrieve the result of a JDBC call

This way blocking calls would be executed inside a separate executor. Here is a simple [example](https://gist.github.com/eduard-vasinskyi/ba4c81fc063300e0c46bc57dc2b10b05) that demonstrates handling JDBC calls.

**Comment by hjldev** [comment]
@eduard-vasinskyi Very useful to me, thank you
