### ISSUE TITLE
Serving public resources like CSS and images

### ISSUE THREAD

**Issue by Kilobyte1000** [activej/activej#65]
How can I serve CSS and images alongside the HTML document? I tried using `Static Servlet`'s `addIndexResources` to no avail

**Comment by eduard-vasinskyi** [comment]
Hello, @Kilobyte1000 
You can refer to an [example](https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/StaticServletExample.java) which demonstrates how to serve static content (`.html`, `.js`, `.css`) using [StaticServlet](https://github.com/activej/activej/blob/master/core-http/src/main/java/io/activej/http/StaticServlet.java)

In an example, we serve static resources from a classpath (`resources/static/site` directory). That's why we have used `StaticServlet.ofClassPath(executor, "static/site")`. If your public resources are not located in a classpath, you may use 
`public static StaticServlet ofPath(Executor executor, Path path)` method and specify the location of files to be served.

`StaticServlet#withIndexResources` method is used to instruct the servlet which files should be loaded for an HTTP request that contains either an empty path (`/`) or a path to some inner directory. 
In the example, we use `StaticServlet#withIndexHtml` to instruct the servlet to look for the 'index.html' file.

**Comment by Kilobyte1000** [comment]
Thanks. I didn't realise I had to add separate routes for the public resources too
