### ISSUE TITLE
Minimal multithreaded server example

### ISSUE THREAD

**Issue by FireMasterK** [activej/activej#69]
I took a look at https://activej.io/workers.html and [MultithreadedHttpServerLauncher.java](https://github.com/activej/activej/blob/v4.1/launchers/http/src/main/java/io/activej/launchers/http/MultithreadedHttpServerLauncher.java), but I fail to understand what is a simple way to do so.

Here's what I'm currently doing:
```
public class ServerLauncher extends Launcher {

    @Provides
    Eventloop eventloop() {
        return Eventloop.create();
    }

    @Provides
    WorkerPool workerPool(WorkerPools workerPools) {
        return workerPools.createPool(128);
    }

    @Provides
    AsyncServlet servlet() {

        RoutingServlet router = RoutingServlet.create()/* removed */;

        return new CustomServletDecorator(router);
    }

    @Provides
    @Eager
    AsyncHttpServer server(Eventloop eventloop, AsyncServlet servlet) {
        return AsyncHttpServer.create(eventloop, servlet).withListenPort(Constants.PORT);
    }

    @Override
    protected Module getModule() {
        return combine(ServiceGraphModule.create(), WorkerPoolModule.create());
    }

    @Override
    protected void run() throws Exception {
        awaitShutdown();
    }
}
```

I have tried adding @Worker to the `servlet()` method, but that gives me an error saying `Unsatisfied dependencies detected`.

When I tested my application without this, it was only able to accept one request at a time.

I perform a lot of network-related IO in the router, I'm a bit uncertain on what kind of thread model I should use.

**Comment by FireMasterK** [comment]
I found https://github.com/the-benchmarker/web-frameworks/blob/master/java/activej/src/main/java/benchmark/io/activej/http/Main.java which is a much smaller example, I set the workers to 128, would there be any issue in doing so?

**Comment by dvolvach** [comment]
Hi @FireMasterK 

ActiveJ supports one or many 'eventloop' threads for I/O, but in addition you can always use regular Java threads, thread pools, executors, etc. ActiveJ threading model can be compared to highly scalable threading model of NodeJS, but greatly enhanced - unlike NodeJS, you can use multiple 'eventloop' threads, plus extensive Java multithreading capabilities.

Even a single 'eventloop' thread makes it perfectly possible to process tens of thousands of complex concurrent requests, which involve lots of concurrent async I/O, complex computations etc. ActiveJ has been designed exactly for this scenario. 

In any case, just like in NodeJS, you must avoid blocking I/O operations and CPU-intensive operations in your 'eventloop' threads - otherwise all concurrent I/O operations in your 'eventloop' thread would be blocked too.
This can be done in two ways:

- offloading all blocking I/O operations and CPU-intensive operations into separate Java threads or thread pools:
https://github.com/activej/activej/blob/master/examples/core/http/src/main/java/BlockingServletExample.java
https://github.com/activej/activej/blob/master/examples/core/sql/src/main/java/UserServiceExample.java
- even better alternative is to replace your blocking I/O operations with ActiveJ non-blocking alternatives, like Promises:
https://github.com/activej/activej/tree/master/examples/core/promise/src/main/java

> the workers to 128, would there be any issue in doing so?

Even if your 'eventloop' threads are not doing any blocking I/O operations, it does not make sense to exceed the number of physical CPU cores for 'eventloop' threads (the maximum thoroughput cannot exceed the total power of your CPUs, but the latency would suffer). And all blocking I/O operations must be avoided anyway, like it is described above.

So, in your case, you can consider using single 'eventloop' application as a good starting point for initial development, and at later time you can always easily scale your application to multithreaded application.

**Comment by FireMasterK** [comment]
Thank you!

I ended up going with `AsyncServlet.ofBlocking` for now, in the future I will try using promises.
