### ISSUE TITLE
Eventloop

### ISSUE THREAD

**Issue by azzahrah** [activej/activej#86]
We are working with activej-eventloop to prevent syncronize process overhead, my thread model like this

```
class MyThread extends Thread{
 private Eventloop eventlooop;
   public MyThread(Eventloop eventloop){
   }
 
@Override
 public void run(){
   eventloop.keepalive(true);
    eventloop.run();
 }
}  
```

we are use eventloop in antoher class to post / execute many runnable process
```
class HandlerIncomingMessage{
 Eventloop eventloop;
public HandlerIncomingMessage(Eventloop eventloop){
    this.eventloop=eventloop;
}
 private function void addEvent(Runnable r){
     //this happend 1000/second
      eventllop.post(r);
  }

public void start(){
  //dummy start incoming message

 addEvent(()->{
   //processing receive data here..
});
}
```

main app

```
  Eventloop el = Eventloop.Create();

HandlerIncomingMessage him=new HandlerIncomingMessage(el);

MyThread mt=new MyThread(el);
  mt.start();

```
my question:
1. inside eventloop final class contain loop variable, can it cause buffroverflow if not reset?
2. what tick() function inside eventloop? is this userfull function for common usage?

**Comment by eduard-vasinskyi** [comment]
Hello, @azzahrah
I didn't quite get the first question. Could you rephrase, please? 

`Loop` variable inside [Eventloop](https://github.com/activej/activej/blob/master/core-eventloop/src/main/java/io/activej/eventloop/Eventloop.java) indicates how many cycles(loops) of Eventloop have passed. Each loop consists of several steps, such as processing IO keys returned from `selector.select()` call, executing tasks (local, concurrent, scheduled, etc.). Execution of each such task is called a tick. You can read more about Eventloop [here](https://activej.io/eventloop.html)

A `tick()` method of Eventloop returns a unique identifier of a current tick (current loop combined with a current tick within a loop).

The returned value can be used to check whether or not some task was executed asynchronously or not. One common usage is this: 
- Call `tick()` and save the result
- Create a promise or some other possibly asynchronous task
- Inside the promise/task callback call `tick()` once again and compare with the previous value of `tick()`
- If it is the same, the task was executed within the same tick, otherwise, the task was executed asynchronously
- 
This is useful for some asynchronous algorithms. However, it is possible that we mark this method as deprecated in future versions of ActiveJ.

**Comment by azzahrah** [comment]
@eduard-vasinskyi for second answer its clear, its like to calculate elapse time...
for first question: this actual process occurred in my app, we post runnable more than 1000 in 1 second to eventloop, and my app more than 30days without closed/reset....  so can it cause buffroverflow?

**Comment by eduard-vasinskyi** [comment]
@azzahrah 
Well, it depends on how much time a runnable takes to be executed. If it is less than 1 ms (1s / 1000 tasks) then there probably will be no buffer overflow.
 
By the way, if you are adding tasks to the eventloop from a thread other than the eventloop thread you should be using `Eventloop#execute` rather than `Eventloop#post`

**Comment by azzahrah** [comment]
@eduard-vasinskyi thank for advice...

**Comment by eduard-vasinskyi** [comment]
@azzahrah, a slight clarification: task overflow depends both on the rate of adding new tasks as well as on time it takes the eventloop to execute them. If the former exceeds the latter, the overflow would happen.
To prevent the task queue from overflowing we use several approaches:
Queue overflow control or throttling
Suspend/resume mechanism of ‘Datastream’ module (e.g. backpressure propagation)
Pull/push mechanism of ‘CSP’ module which guarantees sequential task execution
Regarding your task, if you are sure that the rate of task execution is higher than the rate of adding new tasks, you can leave it as-is. Otherwise, you should think of a way to control the rate of new tasks being added to the eventloop, similar to one of the above.
