### ISSUE TITLE
Error occurs in example from tutorial.

### ISSUE THREAD

**Issue by Danilo3** [activej/activej#90]
Error occured [in this example](https://activej.io/tutorials/template-engine-integration.html) when I tried to create poll (open "/create" path and click add button).
Main error message : 

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public final java.lang.Object java.util.HashMap$Node.getKey() accessible: module java.base does not "opens java.util" to unnamed module @39fb3ab6

Full log in file: [ActiveJ_Error.txt](https://github.com/activej/activej/files/6580198/ActiveJ_Error.txt)
[This solution](https://stackoverflow.com/a/67606115) worked for me:

> add to VM options --add-opens java.base/java.util=ALL-UNNAMED

**Comment by eduard-vasinskyi** [comment]
Hello, @Danilo3
The problem is caused by illegal reflective access in the [mustache](https://github.com/spullara/mustache.java) library. However, the problem seems to be fixed in newer versions of `mustache`. We have updated example dependencies to the latest `mustache` version - 0.9.10. Now, running the example does not lead to `InaccessibleObjectException`
Thank you for spotting this one!
